// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpQT_p7vmkwjDMhQHFrfIUZ7sACfZu7GI',
    appId: '1:29392231336:web:d3692e57ffa76dc1781b9d',
    messagingSenderId: '29392231336',
    projectId: 'vistalk-f9593',
    authDomain: 'vistalk-f9593.firebaseapp.com',
    storageBucket: 'vistalk-f9593.appspot.com',
    measurementId: 'G-RT5J9ZQ2GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVFbPWZvNZ1lsatwhkF1IImAvkjKcfQIE',
    appId: '1:29392231336:android:a5428c47c0a38b53781b9d',
    messagingSenderId: '29392231336',
    projectId: 'vistalk-f9593',
    storageBucket: 'vistalk-f9593.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzqTzZxutQ50jcB_H4UPOBhf_HlJPHiEc',
    appId: '1:29392231336:ios:4e96d293760a3574781b9d',
    messagingSenderId: '29392231336',
    projectId: 'vistalk-f9593',
    storageBucket: 'vistalk-f9593.appspot.com',
    iosBundleId: 'com.example.vistalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzqTzZxutQ50jcB_H4UPOBhf_HlJPHiEc',
    appId: '1:29392231336:ios:b9536c5f65399772781b9d',
    messagingSenderId: '29392231336',
    projectId: 'vistalk-f9593',
    storageBucket: 'vistalk-f9593.appspot.com',
    iosBundleId: 'com.example.vistalk.RunnerTests',
  );
}
